# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fn_Sto <- function(t, q, gamma_all, px, pw) {
    .Call(`_MuSICg_fn_Sto`, t, q, gamma_all, px, pw)
}

fn_cfto <- function(t, q, gamma_all, px, pw) {
    .Call(`_MuSICg_fn_cfto`, t, q, gamma_all, px, pw)
}

fn_dexpQ <- function(cstat, t1, t2, q, Xi, gamma_all, len_par) {
    .Call(`_MuSICg_fn_dexpQ`, cstat, t1, t2, q, Xi, gamma_all, len_par)
}

fn_dg <- function(t, gamma_all, len_par) {
    .Call(`_MuSICg_fn_dg`, t, gamma_all, len_par)
}

fn_dh <- function(t, gamma_all, len_par) {
    .Call(`_MuSICg_fn_dh`, t, gamma_all, len_par)
}

fn_egval <- function(q) {
    .Call(`_MuSICg_fn_egval`, q)
}

fn_egvec <- function(q) {
    .Call(`_MuSICg_fn_egvec`, q)
}

fn_expQ <- function(cstat, t1, t2, q, gamma_all) {
    .Call(`_MuSICg_fn_expQ`, cstat, t1, t2, q, gamma_all)
}

fn_fto <- function(t, q, gamma_all, px, pw) {
    .Call(`_MuSICg_fn_fto`, t, q, gamma_all, px, pw)
}

fn_g <- function(t, gamma_all) {
    .Call(`_MuSICg_fn_g`, t, gamma_all)
}

fn_h <- function(t, gamma_all) {
    .Call(`_MuSICg_fn_h`, t, gamma_all)
}

fun_lik_incident_grad <- function(uID, ID, visits, states, Qe, X_ID, cen, gamma_all, len_par) {
    .Call(`_MuSICg_fun_lik_incident_grad`, uID, ID, visits, states, Qe, X_ID, cen, gamma_all, len_par)
}

fun_lik_incident_grad_i <- function(ids, ID, visits, states, Qe, X_ID, cen, gamma_all, len_par) {
    .Call(`_MuSICg_fun_lik_incident_grad_i`, ids, ID, visits, states, Qe, X_ID, cen, gamma_all, len_par)
}

fn_lik_prevalent <- function(u_ID, v_ID, Qe, cen, gamma_all, eta, k, px, pw, px21, px22, pw2) {
    .Call(`_MuSICg_fn_lik_prevalent`, u_ID, v_ID, Qe, cen, gamma_all, eta, k, px, pw, px21, px22, pw2)
}

fn_lik_prevalent_exp <- function(u_ID, v_ID, Qe, cen, gamma_all, eta, px, pw, px21, px22, pw2) {
    .Call(`_MuSICg_fn_lik_prevalent_exp`, u_ID, v_ID, Qe, cen, gamma_all, eta, px, pw, px21, px22, pw2)
}

fn_lik_prevalent_grad <- function(u_ID, v_ID, X_ID, Qe, cen, gamma_all, eta, k, px, pw, px21, px22, pw2, len_par) {
    .Call(`_MuSICg_fn_lik_prevalent_grad`, u_ID, v_ID, X_ID, Qe, cen, gamma_all, eta, k, px, pw, px21, px22, pw2, len_par)
}

fn_lik_prevalent_grad_i <- function(id, u_ID, v_ID, X_ID, Qe, cen, gamma_all, eta, k, px, pw, px21, px22, pw2, len_par) {
    .Call(`_MuSICg_fn_lik_prevalent_grad_i`, id, u_ID, v_ID, X_ID, Qe, cen, gamma_all, eta, k, px, pw, px21, px22, pw2, len_par)
}

fn_lik_prevalent_grad_i_exp <- function(id, u_ID, v_ID, X_ID, Qe, cen, gamma_all, eta, px, pw, px21, px22, pw2, len_par) {
    .Call(`_MuSICg_fn_lik_prevalent_grad_i_exp`, id, u_ID, v_ID, X_ID, Qe, cen, gamma_all, eta, px, pw, px21, px22, pw2, len_par)
}

fn_lik_prevalent_i <- function(id, u_ID, v_ID, Qe, cen, gamma_all, eta, k, px, pw, px21, px22, pw2) {
    .Call(`_MuSICg_fn_lik_prevalent_i`, id, u_ID, v_ID, Qe, cen, gamma_all, eta, k, px, pw, px21, px22, pw2)
}

fn_lik_prevalent_i_exp <- function(id, u_ID, v_ID, Qe, cen, gamma_all, eta, px, pw, px21, px22, pw2) {
    .Call(`_MuSICg_fn_lik_prevalent_i_exp`, id, u_ID, v_ID, Qe, cen, gamma_all, eta, px, pw, px21, px22, pw2)
}

fn_lik_prevalent_i_length <- function(id, u_ID, v_ID, Qe, cen, gamma_all, tau, px, pw, px21, px22, pw2) {
    .Call(`_MuSICg_fn_lik_prevalent_i_length`, id, u_ID, v_ID, Qe, cen, gamma_all, tau, px, pw, px21, px22, pw2)
}

fn_lik_prevalent_length <- function(u_ID, v_ID, Qe, cen, gamma_all, tau, px, pw, px21, px22, pw2) {
    .Call(`_MuSICg_fn_lik_prevalent_length`, u_ID, v_ID, Qe, cen, gamma_all, tau, px, pw, px21, px22, pw2)
}

fn_sumxtx <- function(x) {
    .Call(`_MuSICg_fn_sumxtx`, x)
}

fun_dQ <- function(q, xi, gamma_all, len_par) {
    .Call(`_MuSICg_fun_dQ`, q, xi, gamma_all, len_par)
}

fun_lik_incident <- function(uID, ID, visits, states, Qe, X_ID, cen, gamma_all) {
    .Call(`_MuSICg_fun_lik_incident`, uID, ID, visits, states, Qe, X_ID, cen, gamma_all)
}

fun_lik_incident_i <- function(ids, ID, visits, states, Qe, X_ID, cen, gamma_all) {
    .Call(`_MuSICg_fun_lik_incident_i`, ids, ID, visits, states, Qe, X_ID, cen, gamma_all)
}

